cursor #eddfe3
cursor_text_color #d4c2c8

foreground            #eddfe3
background            #181115
selection_foreground  #402a35
selection_background  #dfbecc
url_color             #fbb0d7

color0   #181115
color1   #ff727b
color2   #9ffb7d
color3   #ffe072
color4   #ee98c5
color5   #743455
color6   #fbb0d7
color7   #ffeff7
color8   #a3969d
color9   #ff9fa5
color10  #bdffa5
color11  #ffeba5
color12  #ffbedf
color13  #ffc9e5
color14  #ffdcee
color15  #fff8fb
