cursor #e8e2d5
cursor_text_color #ccc6b5

foreground            #e8e2d5
background            #15130c
selection_foreground  #353117
selection_background  #cfc7a2
url_color             #d6c871

color0   #15130c
color1   #f67c6e
color2   #79d66b
color3   #ffe872
color4   #cbbb58
color5   #63570d
color6   #d6c871
color7   #e0ded3
color8   #8b8980
color9   #ffa99f
color10  #b1ffa5
color11  #fff0a5
color12  #ebde8c
color13  #fff3aa
color14  #fff7c8
color15  #fffef8
